# Build the demo from examples for WebAssembly and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Xvfb
      run: |
        Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Build
      run: env GOOS=js GOARCH=wasm go build -v -o ./docs/demo.wasm ./examples/...

    - name: Test
      run: go test -v ./...
